---
title: "HW12 - Poisson Regression"
author: "Madhu Peduri"
date: "`r format(Sys.time(), '%B %e, %Y')`"
output:
  html_document:
    df_print: paged
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    highlight: tango
    number_sections: yes
subparagraph: yes
header-includes: \usepackage{hyperref} \usepackage{framed,xcolor} \definecolor{shadecolor}{rgb}{0.99,
  0.95, 0.9} \renewcommand\arraystretch{1.5} \usepackage[none]{hyphenat} \raggedright
  \usepackage{amsmath, amsthm, amssymb, bm}
---

  
```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
library(rmarkdown)
library(graphics)
library(ggplot2)
library(MASS)
library(Hmisc)
library(epiDisplay)
library(vcd)
library(mnormt)
library(MASS)
library(car)
library(ggpubr)
library(PairedData)
library(lmtest)
library(xtable)
library(faraway)
library(leaps)
library(psych)
library(Matrix)
library(dobson)
library(jtools)
library(Rcpp)
options(digits = 3)
opts_chunk$set(tidy.opts=list(width.cutoff=60), tidy=TRUE)
```

### Problem 1  

```{r}
# Convert the doctors dataframe to appropriate format
doc <- data.frame(
  age       = as.numeric(unclass(as.factor(doctors$age))), 
  agesq     = (as.numeric(unclass(as.factor(doctors$age))))^2,
  agecat    = as.character(doctors$age),
  smoke     = as.numeric(unclass(as.factor(doctors$smoking))),
  deaths    = as.numeric(doctors$deaths),
  personyrs = as.numeric(doctors$'person-years')
)
doc
des(doc)
```

### Problem 1(a)

```{r}
# GLM model 
poismod <- glm(deaths ~ age + agesq + smoke + smoke:age, offset = log(personyrs), family = poisson(link = "log"), data = doc)

sumpois <- summary(poismod)
sumpois
summpois <- summ(poismod, confint = TRUE, digits = 3, ci.width = 0.95)

sprintf("Residual deviance of the poisson model : %.3f",sumpois$deviance)
sprintf("Residual degrees of freedom of the poisson model : %.3f",sumpois$df.residual)
print("Pseudo R2 (Mcfadden) of the model : 0.943")
```

## Document Information.

All of the statistical analyses in this document will be performed using `r R.version.string`.  R packages used will be maintained using the [packrat](http://rstudio.github.io/packrat/) dependency management system.  

```{r session-info}
sessionInfo()
```
