# Include the packages
library(graphics)
library(ggplot2)
library(MASS)
library(Hmisc)
library(epiDisplay)
library(vcd)
library(mnormt)
library(MASS)
library(car)
library(ggpubr)
library(PairedData)
library(lmtest)
library(xtable)
library(faraway)
library(leaps)
library(psych)
library(Matrix)
library(dobson)
library(jtools)
library(Rcpp)

wdt <- read.csv("Data\\website.csv")
wd <- wdt
print(as.factor(as.character(wdt$year)))
wdt$year <- as.character(wdt$year)
wdt$year <- as.numeric(unclass(as.factor(wdt$year)))
headTail(wdt)
wd2001 <- wd[wd$year == 2001,]
head(wd2001)
rn <- names(wdt)
rmv <- c("ï..idnum","delivered")
setdiff(rn,rmv)
