---
title: "Project"
author: "Madhu Peduri"
date: "`r format(Sys.time(), '%B %e, %Y')`"
output:
  html_document:
    df_print: paged
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    highlight: tango
    number_sections: yes
subparagraph: yes
header-includes: \usepackage{hyperref} \usepackage{framed,xcolor} \definecolor{shadecolor}{rgb}{0.99,
  0.95, 0.9} \renewcommand\arraystretch{1.5} \usepackage[none]{hyphenat} \raggedright
  \usepackage{amsmath, amsthm, amssymb, bm}
---

  
```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
library(rmarkdown)
library(graphics)
library(ggplot2)
library(MASS)
library(Hmisc)
library(epiDisplay)
library(vcd)
library(mnormt)
library(MASS)
library(car)
library(ggpubr)
library(PairedData)
library(lmtest)
library(xtable)
library(faraway)
library(leaps)
library(psych)
library(Matrix)
library(dobson)
library(jtools)
library(Rcpp)
library(pscl)
library(effects)
options(digits = 3)
opts_chunk$set(tidy.opts=list(width.cutoff=60), tidy=TRUE)
```

### Functions

```{r}

cfac <- function(x, breaks = NULL) {
 if(is.null(breaks)) breaks <- unique(quantile(x, 0:10/10))
 x <- cut(x, breaks, include.lowest = TRUE, right = FALSE)
 levels(x) <- paste(breaks[-length(breaks)], ifelse(diff(breaks) > 1,
 c(paste("-", breaks[-c(1, length(breaks))] - 1, sep = ""), "+"), ""),
 sep = "")
 return(x)
}

clog <- function(x) log(x + 0.5)

modelstat <- function(mod,dtf){
  # Summaries
  mods1 <- summary(mod)
  mods2 <- summ(mod, confint = TRUE, digits = 3, ci.width = 0.95)
  
  # Attributes
  mods2atr <- attributes(mods2)
  
  # stat
  print(kable(cbind( na.omit(summary(mod)$coef) ,RR= na.omit(coef(mod)), na.omit(confint(mod)) )))
  
  # Goodness of fit
  devresd <- round(residuals(mod, type = "deviance"), 3)
  devgof <- sum(devresd^2)
  
  pearson.resid <- round(resid(mod, type = "pearson"), 3)
  prsgof <- sum(pearson.resid^2)
  
  # Residual plots 
  stddevres <- rstandard(mod)
  stdpearsons <- rstandard(mod, type = "pearson")
  
  # par(mfrow = c(2, 2))
  # plot(log(predict(mod)), devresd, ylab = "residuals")
  # abline(h = 0)
  # plot(log(predict(mod)), stddevres, ylab = "Standardized residuals")
  # abline(h = 0)
  # plot(log(predict(mod)), pearson.resid, ylab = "pearson residuals")
  # abline(h = 0)
  # plot(log(predict(mod)), stdpearsons, ylab = "pearson Standardized residuals")
  # abline(h = 0)
  
  # Predicted value plots
  # expected <- round(predict(mod, type = "response"), 2)
  # par(mfrow = c(1, 2))
  # plot(dtf$delivered, ylab = "Actual")
  # plot(expected, ylab = "Predicted")
  
  # plots
  par(mfrow = c(2, 2))
  # plot(log(fitted(mod)), (dtf$delivered - fitted(mod))^2,
  #   xlab = expression(hat(mu)), ylab = expression((y - hat(mu))^2))
  # abline(0, 1)
  plot(mod, which = c(1), main = "", caption = "")
  halfnorm(residuals(mod))
  #shapiro.qqnorm(residuals(mod, type = "deviance"))
  plot(mod, which = c(2), main = "", caption = "")
  influencePlot(mod)
  
  # par(mfrow = c(2, 2))
  # plot(mod)
  
  # Step for model selection 
  # if(mods2atr$lmFamily$family != "quasipoisson"){
  #   step(mod)
  # }
  
  #poisson gof
  chiq <- pchisq(deviance(mod), df.residual(mod), lower = F)
  
  c(mods1$deviance,mods1$df.residual,chiq,mods2atr$rsqmc,mods2atr$aic,mods2atr$bic,devgof,prsgof)
}
```

### Step 1: Read the data

```{r}
# Read and describe the data
wd <- read.csv("Data\\website.csv")
```

### Step 2: Explore the data

```{r}
# Summary of the data
wd
des(wd)
summary(wd)
wdfm <- as.data.frame(sapply(wd,function(x) cbind(summary(x))))
row.names(wdfm) <- c('Min','1st Qu','Median','Mean','3rd Qu','Max')
wdfm

# Check the assumption of response variable
sprintf("Square root of the Mean of the response : %.3f", sqrt(mean(wd$delivered)))
sprintf("Standard Deviation of the response : %.3f", sd(wd$delivered))

# Plot the label
counts <- table(wd$delivered)
par(mfrow = c(1, 2))
plot(wd$delivered, xlab='Index', ylab='Websites Delivered',main='Scatter plot')
abline(h=c(sqrt(mean(wd$delivered)),sd(wd$delivered)),col=c('blue','red'))
text(69,9.0,'Std Dev',cex=0.6,col='red')
text(66,4.0,'Sqrt(mean)',cex=0.6,col='blue')
barplot(counts, xlab='Websites Delivered', ylab='Frequency',main='Counts plot')

#Plot the continous variables.
par(mfrow = c(1, 2))
plot(wd$backlog,ylab='Backlog')
plot(wd$experience,ylab='Experience')

# Plot the categorical variables
par(mfrow = c(1, 3))
barplot(table(wd$change),xlab='Change')
barplot(table(wd$year),xlab='Year')
barplot(table(wd$quarter),xlab='Quarter')

# Plot the categorical variables & Response variable
par(mfrow = c(1, 2))

counts <- table(wd$year,wd$change)
barplot(counts,col=c('gray48','gray100'),legend = rownames(counts),xlab='Change',ylab='Year')

counts <- table(wd$change,wd$delivered)
barplot(counts,col=c('gray48','gray100'),legend = rownames(counts),xlab='delivered',ylab='change')

par(mfrow = c(1, 3))

counts <- table(wd$year,wd$delivered)
barplot(counts,col=c('gray48','gray100'),legend = rownames(counts),xlab='delivered',ylab='year')

wd2001 <- wd[wd$year == '2001',]
counts <- table(wd2001$quarter,wd2001$delivered)
barplot(counts,col=c('gray8','gray30','gray66','gray100'),legend = rownames(counts),xlab='delivered',ylab='quaerter-2001')

wd2002 <- wd[wd$year == '2002',]
counts <- table(wd2002$quarter,wd2002$delivered)
barplot(counts,col=c('gray8','gray30','gray66','gray100'),legend = rownames(counts),xlab='delivered',ylab='quaerter-2002')

# Plot the continous variables
par(mfrow = c(1, 3))
plot(wd$delivered ~ wd$backlog,xlab='backlog',ylab='delivered')
plot(wd$delivered ~ wd$teamnum,xlab='team number',ylab='delivered')
plot(wd$delivered ~ wd$experience,xlab='experience',ylab='delivered')

# Data transformation
names(wd)[1] = "id"
#wd$year <- as.character(wd$year)
#wd$year <- as.numeric(unclass(as.factor(wd$year)))
wdf <- data.frame(
  delivered = as.numeric(wd$delivered),
  backlog = as.numeric(wd$backlog),
  teamnum = as.numeric(wd$teamnum),
  experience = as.numeric(wd$experience),
  change_0 = as.numeric(wd$change),
  change_1 = as.numeric(wd$change),
  year_01 = as.numeric(wd$year),
  year_02 = as.numeric(wd$year),
  quarter_1 = as.numeric(wd$quarter),
  quarter_2 = as.numeric(wd$quarter),
  quarter_3 = as.numeric(wd$quarter),
  quarter_4 = as.numeric(wd$quarter)
)

wdf$change_0[wdf$change_0 == 0] <- 1
wdf$change_0[wdf$change_0 == 1] <- 0
wdf$change_1[wdf$change_1 == 0] <- 0
wdf$change_1[wdf$change_1 == 1] <- 1

wdf$year_01[wdf$year_01 == 2001] <- 1
wdf$year_01[wdf$year_01 == 2002] <- 0
wdf$year_02[wdf$year_02 == 2001] <- 0
wdf$year_02[wdf$year_02 == 2002] <- 1
 
wdf$quarter_1[wdf$quarter_1 != 1] <- 0
wdf$quarter_1[wdf$quarter_1 == 1] <- 1
wdf$quarter_2[wdf$quarter_2 != 2] <- 0
wdf$quarter_2[wdf$quarter_2 == 2] <- 1
wdf$quarter_3[wdf$quarter_3 != 3] <- 0
wdf$quarter_3[wdf$quarter_3 == 3] <- 1
wdf$quarter_4[wdf$quarter_4 != 4] <- 0
wdf$quarter_4[wdf$quarter_4 == 4] <- 1


wdf

# Univariate analysis
#glm plots
par(mfrow = c(1, 3))
glm1 <- glm(delivered ~ backlog, family = poisson(link = "log"),data = wdf)
glm1stat <- modelstat(glm1,wdf)
instatdf <- data.frame(rbind(glm1stat))
rownames(instatdf)[1] <- 'Backlog'
names(instatdf) <- c('Deviance','Dof','Chisq','R2','AIC','BIC','Gof-Dev','Gof-Pearson')
plot(wd$delivered ~ wd$backlog, cex = 1.5, cex.lab = 1.5, las = 1,
    cex.main = 1.5, xlab = "backlog", ylab = "Websites delivered")
abline(glm1, lwd = 2, col = "red")

# glm2 <- glm(delivered ~ teamnum, family = poisson(link = "log"), data = wdf)
# glm2stat <- modelstat(glm2,wdf)
# instatdf <- data.frame(rbind(instatdf,glm2stat))
# rownames(instatdf)[2] <- 'Teamnum'
# plot(wd$delivered ~ wd$teamnum, cex = 1.5, cex.lab = 1.5, las = 1,
#     cex.main = 1.5, xlab = "teamnum", ylab = "Websites delivered")
# abline(glm2, lwd = 2, col = "red")

glm3 <- glm(delivered ~ experience, family = poisson(link = "log"), data = wdf)
glm3stat <- modelstat(glm3,wdf)
instatdf <- data.frame(rbind(instatdf,glm3stat))
rownames(instatdf)[2] <- 'Experience'
plot(wd$delivered ~ wd$experience, cex = 1.5, cex.lab = 1.5, las = 1,
    cex.main = 1.5, xlab = "experience", ylab = "Websites delivered")
abline(glm3, lwd = 2, col = "red")

instatdf

# glm models

# Base model1
rmv <- c("id","delivered","teamnum")
cn <- names(wd)
cn <- setdiff(cn,rmv)
cn <- c(cn,"backlog:experience")
fm <- as.formula(paste("delivered", paste(cn, collapse = "+"), sep = "~"))
glm4 <- glm(fm,family = poisson(link = "log"), data = wd)
glm4stat <- modelstat(glm4,wd)
statdf <- data.frame(rbind(glm4stat))
rownames(statdf)[1] <- 'Base'
names(statdf) <- c('Deviance','Dof','Chisq','R2','AIC','BIC','Gof-Dev','Gof-Pearson')

# Model2 after encoding categorical variables.
rmv <- c("delivered","teamnum")
cn <- names(wdf)
cn <- setdiff(cn,rmv)
cn <- c(cn,"backlog:experience")
fm <- as.formula(paste("delivered", paste(cn, collapse = "+"), sep = "~"))
glm5 <- glm(fm,family = poisson(link = "log"), data = wdf)
glm5stat <- modelstat(glm5,wdf)
statdf <- data.frame(rbind(statdf,glm5stat))
rownames(statdf)[2] <- 'Encoded for Categorical'

# Model3 after removing outliers
rmv <- c("delivered","teamnum")
cn <- names(wdf)
cn <- setdiff(cn,rmv)
cn <- c(cn,"backlog:experience")
fm <- as.formula(paste("delivered", paste(cn, collapse = "+"), sep = "~"))
glm6 <- glm(fm,family = poisson(link = "log"), data = wdf[-c(21,33,61, 65,66),])
glm6stat <- modelstat(glm6,wdf[-c(21,33,61, 65,66),])
statdf <- data.frame(rbind(statdf,glm6stat))
rownames(statdf)[3] <- 'Without Outliers'

# Model4 using quasi-poisson family
rmv <- c("delivered","teamnum")
cn <- names(wdf)
cn <- setdiff(cn,rmv)
cn <- c(cn,"backlog:experience")
fm <- as.formula(paste("delivered", paste(cn, collapse = "+"), sep = "~"))
glm7 <- glm(fm,family = quasipoisson(link = "log"), data = wdf[-c(21,33,61, 65,66),])
glm7stat <- modelstat(glm7,wdf[-c(21,33,61, 65,66),])
statdf <- data.frame(rbind(statdf,glm7stat))
rownames(statdf)[4] <- 'Quasi-poisson'

# Model5 using Negative binomial regression due to the presence of overdispersion
rmv <- c("delivered","teamnum")
cn <- names(wdf)
cn <- setdiff(cn,rmv)
cn <- c(cn,"backlog:experience")
fm <- as.formula(paste("delivered", paste(cn, collapse = "+"), sep = "~"))
glm8 <- glm.nb(fm, data = wdf[-c(21,33,61, 65,66),])
glm8stat <- modelstat(glm8,wdf[-c(21,33,61, 65,66),])
statdf <- data.frame(rbind(statdf,glm8stat))
rownames(statdf)[5] <- 'Negative Binomial'

glm9 <- hurdle(formula = delivered ~ experience + quarter_3 + quarter_1 + year_01, data = wdf[-c(21,33,61, 65,66),], dist = "negbin")
#glm9stat <- modelstat(glm9,wdf[-c(21,33,61, 65,66),])
summary(glm9)
waldtest(glm9)

statdf
```

## Document Information.

All of the statistical analyses in this document will be performed using `r R.version.string`.  R packages used will be maintained using the [packrat](http://rstudio.github.io/packrat/) dependency management system.  

```{r session-info}
sessionInfo()
```
